export const CATEGORIES_ACTION_TYPES = {
  UPDATE_CATEGORIES_SUCCESS: "categories/UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_START: "categories/UPDATE_CATEGORIES_START",
  UPDATE_CATEGORIES_ERROR: "categories/UPDATE_CATEGORIES_ERROR",
};
